# Generated by Django 4.2.6 on 2023-10-22 01:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('shopping_cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_quantity', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
