export const STORE_DETAILS_REQUEST = "STORE_DETAILS_REQUEST"
export const STORE_DETAILS_SUCCESS = "STORE_DETAILS_SUCCESS"
export const STORE_DETAILS_FAIL = "STORE_DETAILS_FAIL"

export const STORE_CREATE_TICKET_REQUEST = "STORE_CREATE_TICKET_REQUEST"
export const STORE_CREATE_TICKET_SUCCESS = "STORE_CREATE_TICKET_SUCCESS"
export const STORE_CREATE_TICKET_FAIL = "STORE_CREATE_TICKET_FAIL"
export const STORE_CREATE_TICKET_RESET = "STORE_CREATE_TICKET_RESET"