export const CUSTOMER_LOGIN_REQUEST = 'CUSTOMER_LOGIN_REQUEST';
export const CUSTOMER_LOGIN_SUCCESS = 'CUSTOMER_LOGIN_SUCCESS';
export const CUSTOMER_LOGIN_FAIL = 'CUSTOMER_LOGIN_FAIL';
export const CUSTOMER_LOGOUT = 'CUSTOMER_LOGOUT';

export const CUSTOMER_REGISTER_REQUEST = 'CUSTOMER_REGISTER_REQUEST';
export const CUSTOMER_REGISTER_SUCCESS = 'CUSTOMER_REGISTER_SUCCESS';
export const CUSTOMER_REGISTER_FAIL = 'CUSTOMER_REGISTER_FAIL';

export const CUSTOMER_DETAILS_REQUEST = 'CUSTOMER_DETAILS_REQUEST';
export const CUSTOMER_DETAILS_SUCCESS = 'CUSTOMER_DETAILS_SUCCESS';
export const CUSTOMER_DETAILS_FAIL = 'CUSTOMER_DETAILS_FAIL';
export const CUSTOMER_DETAILS_RESET = 'CUSTOMER_DETAILS_RESET';

export const CUSTOMER_UPDATE_REQUEST = 'CUSTOMER_UPDATE_REQUEST';
export const CUSTOMER_UPDATE_SUCCESS = 'CUSTOMER_UPDATE_SUCCESS';
export const CUSTOMER_UPDATE_FAIL = 'CUSTOMER_UPDATE_FAIL';
export const CUSTOMER_UPDATE_RESET = 'CUSTOMER_UPDATE_RESET';


export const SELLER_LOGIN_REQUEST = 'SELLER_LOGIN_REQUEST';
export const SELLER_LOGIN_SUCCESS = 'SELLER_LOGIN_SUCCESS';
export const SELLER_LOGIN_FAIL = 'SELLER_LOGIN_FAIL';
export const SELLER_LOGOUT = 'SELLER_LOGOUT';